### ISSUE TITLE
Cryptographic Material Encoding—3rd Alternative Binary Encoding

### ISSUE THREAD

**Issue by stevetodd** [decentralized-identity/keri#100]
_Since the binary representation is being directly merged to master rather than developed in a branch then discussed and merged through a pull request, I'll open this as a separate issue._

The kid0001 commentary under the heading [Cryptographic Material Encoding](https://github.com/decentralized-identity/keri/blob/master/kids/kid0001Comment.md#cryptographic-material-encoding) discusses the proposed binary representation of cryptographic material. The section discusses 3 encodings of cryptographic material:

1. **(R) Raw Binary Material with Code**: a tuple of the derivation code (dc) and the raw material (rm): `(dc, rm)`. Best seen as the parsed, in-memory representation.
2. **(T) Base64 Encoding**: the one we're all familiar with and used within the body of the event
3. **(S) Binary Encoding**: this is proposed in the link above

The commentary describes a choice between two options for converting from R to T and R to S: 

1. **Binary-First**: Derivation codes are one or more _8-bit_ tokens. The base64 representation is the concatenation of derivation code and the raw material, which is then base64 encoded. The binary representation is simply the non-base64-encoded concatenated.
2. **base64 code + base64 material**: Derivation codes are one or more _6-bit_ tokens. The base64 representation is the concatenation of the derivation code and the base64-encoded raw material. The binary representation is essentially the base64 representation base64 decoded.

There is a third option, which I would like to propose:

3. **base64 derivation code + (base64 or binary)**: Derivation codes are one or more _6-bit_ tokens, as in option (2). The base64 representation is the same option (2). The binary representation, however, is the base64 representation of the derivation code with the raw material concatenated. Said a different way, the representations of the code itself are equivalent at the binary level.

This third option preserves "the stable derivation code characters in the textual domain" while also simplifying the decoding in the binary domain. Decoding in the textual domain is well understood. In the binary domain, a processor is able to read and interpret the codes as whole bytes and avoids having to do the extra work to extract the six-bit codes from the bytes.

From a compactness standpoint, for one-character-code encodings, the length of bytes is equivalent; option (2) essentially just shifts the raw material 2-bits and leaves 2 empty bits at the end. For two-character codes, it is also the same length since the code will occupy 12-bits, which will require 2 bytes and leave 4 empty bits at the end. For three-character codes (not currently used--a separate topic), the numbers are 3-bytes and 6 empty bits. Finally, it isn't until four-character derivation codes that option two becomes shorter.

This "mixed encoding" representation might seem odd, but perhaps it is better to think of it instead as having a constraint on derivation codes that allows it to be represented in both the textual and binary domain without translation.

**Comment by SmithSamuelM** [comment]
@stevetodd  The third option you propose is not composable when converting from T to S and S to T. the only way to get from T to S is to go through R and to get from S to T is to go through R.  I agree it has stability and comparable compactness and the additional option of 3 character codes,  but without composability we lose the stream processing capabilities of composed streams, archives, logging etc of composed converted in groups. A parser has to sequentially parse each element in order to convert from T to S and vice versa. It has to go through R each time. This is the fundamental limitation of mixed encoding. Composability was the main design goal and reason for using  2. and direct composable S to T transforms.  As outlined in KID0001 commentary composability allows us to create a composable base64 native (T domain) encoding of messages  that  when converted as a composition to S is more compact than CBOR or msgpack.  Nothing in our existing code base has to change.  Given there is very little to gain from 3 relative to our existing code base and switching to 3 would break a lot of code and we lose future advantages of composability. I am very reluctant to support 3.

**Comment by SmithSamuelM** [comment]
@stevetodd Another limitation of 3) not mentioned in your comment but covered in the Commentary is that when the derivation code is identical in the S and T domains there is no way for a parser to know if the attached crypto material is in Base64 or Binary. This means that in order to benefit from a compressed stream where all the primitives show up as Base64 code plus Base2 attached crypto material some other code is needed besides the derivation code. So depending on how those other codes are applied, 3 may end up being less compact. A unique code for attached binary or attached Base64 per primitive may be problematic because the derivation code is part of identifiers and changing code makes it a different identifier not merely a round trippable transform of the whole identifier but a different identifier. A user has to then always convert back to T separably.  As long as one only ever operates in T and R and is not streaming in S then 3 is ok.  But as soon as one wants to convert streams in T into S and vice versa as composable streams then 3 just fails.

**Comment by stevetodd** [comment]
So to say it simply, for the T to S conversion in group material, you want to be able to just run the whole set together through base64_encode and base64_decode for the inverse conversion. By composable, you mean, being able to encode and decode the aggregate.

**Comment by SmithSamuelM** [comment]
@stevetodd Yes!

**Comment by SmithSamuelM** [comment]
Because the native domain for identifier namespaces is Text. It makes Base64 a native domain for KERI, but we want to benefit from easy conversion any aggregate to  binary for streaming  and then convert back to text for sys logging archiving or using in the text domain without having to parse each primitive in the aggregate each conversion. having to parse each primitive separately defeats pipelining, concurrent stream processing etc.  Its not a benefit that is immediately apparent but will be down the road when you look at the actual volume of cryptographic material that KERI will be handling especially in data intensive streaming applications.  Everything everywhere will be signed.  And those signatures, receipts, etc all have to be streamed to/from syslog, databases, and every signature has to be verified so concurrent processing of signatures or heterogeneous groups of crypto material that includes signatures will greatly benefit form aggregated conversion of those streams.

**Comment by SmithSamuelM** [comment]
Signing and verifying every statement (data item) in a processing flow solves the secure attribution problem. It fixes security on the internet in general. So it will really want to have a primitive coding scheme that allows aggregate conversion between the two primary domains for processing information (text and binary).  What happens is that not enabling composability up front we force anyone who wants to do stream conversion at scale into building custom processors to be able to get there.  Its why there is an HTTP2 to enable concurrent streaming at scale. An KERI is already an order of magnitude more compact than http. So if we enable composable stream processing we have built in scalability with a very simple streaming protocol.

**Comment by SmithSamuelM** [comment]
For example the new count codes include generic stream composition operators where a stream processor can prepend the code to any composition of Base64 material (it specifies the length of the ) material and then an intermediate processor can split the stream at that operator and convert the split to Binary for transmission. A later processor (say a splunk logger) who wants to log the stream in text for regex parsing can fork that stream and with both a Base64 converted back and a Binary that goes to a signature/event verifier.  The added complexity of doing the strip and shift in the binary domain is small relative the the complexity and cost of not being able to split streams in aggregates. The former only happens at the end a given branch of a stream, whereas that latter may happen multiple times in the lifecycle of a stream.

**Comment by SmithSamuelM** [comment]
Some of these lessons learned came from my work on the CEA 852.1-ANSI 1513167 protocol. Which is a generic IP tunneling protocol for non-IP protocols. (mainly enabling non-IoT protocols to become IoT protocols). (I was the working group chair)
https://webstore.ansi.org/standards/cea/cea8522014ansi-1513167

And the most important feature of the protocol was extensible composability between the tunneled and non-tunneled domains where the protocol streams lived.  The analogy here is that Streaming Base64 crypto material is one domain and the other domain is streaming binary.  So KERI has it much easier. Almost trivially so. But composability is huge at scale. So I would be hard pressed to give it up.

**Comment by stevetodd** [comment]
> Because the native domain for identifier namespaces is Text. It makes Base64 a native domain for KERI...

Sort of. While most of our interaction with IP addresses, for example, are with its textual representation, the internal representation is binary. If we are talking about generalizing this framing format for a foundational internet protocol, I'm strongly against anything but a binary foundation. Otherwise, we'll be paying the base64 price forever. 

The framing is now emerging as 3-bits at the start of each message describing the frame type. For non-JSON/CBOR/MSGP bodies, you'll have to have a byte to declare it something different. You have described codes for that. So the frame format evolves a type + a length. It we're proxying/load balancing, then we're going to start needing other headers in the frame like source, destination, possibly routing headers. 

I'm not saying that the event body itself shouldn't be textual—I think the frames should carry binary bodies, but if that body happens to be JSON, that's fine. Just like HTTP, we shouldn't care whether the body is textual or binary.

I'm not sure that we'll ever actually need a textual representation of the frame.

**Comment by SmithSamuelM** [comment]
Syslogging, monitoring, archival in a non binary format are all common widespread uses of where a Base64 representation is preferred.  And debugging via Base64 is much much easier especially when you are not the implementer of the protocol but a user. With composability you get that ease for free by merely switching the frame domain for the whole stream, if its composable (but not if its not).  TcpDump and Wireshark are much easier to use on Text than binary. Ever try to write a custom WireShark parser versus just regexing  text output from a TCPDump?   The point is that by supporting S we get both text and binary stream processing for no extra cost. So we don't have to pick now or ever. This also satisfies the hourglass theorem. If my protocol can support two domains for the cost of one then its a more optimal protocol vis a vis hourglass principle. With composiblity we get both domains for the same cost. It matters little that one domain may be much more used than the other. If the cases where the other are used are important if not as common and it comes at little or not cost then it should be a no brainer to pick an approach to supports both. So given its very little extra effort to support the conversion from S to R R to S conversion (which is all we have to pay to get everything else for free) and the R to T and T to R conversion is about the same in either case, tt seems to me to be an easy decision. I suggest that you are willing to give up a lot down the road for what is from an effort point of view at this stage is at best a wash. 

 I am not talking about IP load balancing. I am taking about load balancing of the processing of the signatures and verification and logging. And for that we can do with very little additional effort from a framing header point of view if we support composability.  But it appears that it's not something you see as advantageous.  The fact that you mentioned IP headers makes be believe we aren't talking about the same types of stream processing.

**Comment by SmithSamuelM** [comment]
>  Otherwise, we'll be paying the base64 price forever.

I think thats where we differ. I don't see a Base64 price. If we have composability then we get both Base64 and Binary for the same cost.  All we need is a small piece of code to do a direct conversion from qb2 to (dc, rm) that involves a bit shift. Its not a meaningful cost. It may be annoying and not as elegant as one may prefer. but its not a "forever price". But lack of composability will be a forever price because there is no easy way to achieve it once you close that door.

**Comment by stevetodd** [comment]
> Signing and verifying every statement (data item) in a processing flow solves the secure attribution problem. It fixes security on the internet in general. 

> The fact that you mentioned IP headers makes [me] believe we aren't talking about the same types of stream processing.

We may not be talking about the same thing and I may have incorrectly inferred what you were talking about. It seems like you may be trying to specify a generic protocol where the data payload has secure attribution. If not, we can drop this subthread.

**Comment by SmithSamuelM** [comment]
After an offline discussion with Steve given impartibility with current code base closing issue..
