### ISSUE TITLE
Witness Rotation and Economics (subject of future non-normative section)

### ISSUE THREAD

**Issue by bumblefudge** [decentralized-identity/keri#103]
I am just pulling out one great comment from the KERI <> Cert Transparency thread because I think it should be preserved as an open-issue for later editorial work.

@fimbault wrote:
Ok but "just replace the witnesses" is easy only if you control them somehow (feasible in a corporate setting) or have a public estimate of the trust you can put into them. Otherwise I can hope for the best, choose randomly (supposing they're discoverable) and rerotate if needed, but what if I want more assurances? The question is how do you pick them? how many ? what's the economic model for witnesses?

I think there are many good questions condensed into this paragraph-- maybe only one of them belongs in the spec (how does replacing the witnesses work as one step of the recovery-rotation process), but the others are definitely something to return to after spec is v0.1!

**Comment by SmithSamuelM** [comment]
I agree. The only one in the spec is how to designate witnesses and rotate them.  Some related questions have to do with security.  Because a controller is responsible for witnesses, a controller, can layer on any additional security mechanisms the controller chooses, not merely the signatures of the controller on events sent to witnesses. These could include access control mechanisms (witnesses only accept signed events from the controller who also multi-factor authenticates, or satisfies other access criteria.  All of these make it harder for some attacker beyond merely compromising the controller's keys. As if compromising the controller's private keys isn't hard enough already.

**Comment by chunningham** [comment]
This topic is a sub topic of the use case/non-normative discussion in #120
