### ISSUE TITLE
Proposal for 2 character Labels on message elements

### ISSUE THREAD

**Issue by SmithSamuelM** [decentralized-identity/keri#75]
The current messages use short, 4 character or less labels. This a compromise between over the wire efficiency and understandability. New implementers of the protocol have noted that the short labels are not particularly informative and it may be no worse to just go with shorter 2 character labels. One character labels would loose any semblance of understandability.  It seems that with two character labels they could be abbreviations of two words descriptive labels such that the 2 char abbreviation would still be sufficiently evocative of their meaning as to be useful. 

In the table below, the existing labels are provided in the first column with a primary suggestion and secondary suggestions in successive columns

| Label | Description                                           | New | Alt1 | Alt2 | Alt3 |
|-------|-------------------------------------|-----|-----|------|-----|
| vs    | Version String                                        | vs  |     |    |    |
| pre   | Identifier Prefix                                     | px  | ip  |   |   |
| sn    | Sequence Number                                       | sn  |     |    |   |
| ilk   | Message Kind                                          | mk  | ik  |    |    |
| dig   | Previous Event Digest, Event Digest, Seal Digest      | dg  |  ed  | sd |   |
| sith  | Signing Threshold                                     | st  |     |    |    |
| keys  | List of Signing Keys                                  | ks  | kl  |    |   |
| nxt   | Next Key Set Commitment                               | nx  | nt  | nk |    |
| toad  | Threshold of Accountable Duplicity, Witness Threshold | wt  |     |    |    |
| wits  | List of Witnesses                                     | ws  | wl  |   |   |
| cnfg  | Configuration Data List                               | cd  | cl  | |    |
| cuts  | List of Witnesses to Cut                              | cs  | cl  |  wc   |    |
| adds  | List of Witnesses to Add                              | as  | al  |  wa  |    |
| data  | Payload Data List (Seal List)                             | pd  | pl  | sl |   |
| seal  | Delegator Event Seal                                  | ds  | sl  | es   |    |
| seal  |  Signer Event Seal                                   | ss | es  |    |   |   |
| trait | Configuration Trait                                   | ct  | tt  |    |    |
| root  | Merkle Tree Root Digest                               | rt  | rg  | rd |    |    |
|       | Establishment Only                                    | eo  |     |     |    |
|       | Last Establishment Event                              | le  | ee  |    |    |
|       | Delegated                                             | dd  |     |     |    |
|       | Delegator Prefix                                      | dx  | dp  |    |     |
|       | version number                                       | vn |        |   |   |
|       | event type                                                | et |  |    |    |

**Comment by dlandi** [comment]
Hi Sam,
I think the two-letter scheme is an improvement. Of course, a steady addition of terms might "break the bank" and make this 
scheme untenable. But assuming that you do no foresee an every expanding list of definitions, here are some suggestions. 

Designate a letter to always represent the same word so we can create a reliable key. 
Since there are two positions in the code: [1] and [2], the letter could vary between positions, or a letter could be designated for
both positions, which would allow you to use a letter twice for two different meaning depending on position.

Key:
        [] = denotes position in two-letter code e.g. [1], [2] or [1|2]

i = [2 ]identifier
p = [1] payload
p = [2] prefix
d = [1] delegated or delegator
d = [2] digest
k = [1|2]key(s)
l = [2] list
n = [1]next
w = [2] witness
t = [2] threshold
c = [1] configuration
c = [2] cut
a = [2] add
e = [1] establishment
e = [2] event
o = [2] only 
s = [1]seal
s = [2]sign


Key = Meaning
----------------------------------------------------
vs = Version String			
	
ip = Identifier Prefix			

sn = Sequence Number (as traditional mnemonic)

mk = Message Kind				

dg = Previous Event Digest, 

ed = Event Digest, 

sd = Seal Digest

st = Signing Threshold	

kl = List of Signing Keys		

nk = Next Key Set Commitment	 

wt = Witness Threshold

wl = List of Witnesses		

cl = Configuration Data List	

wc = List of Witnesses to Cut

wa = List of Witnesses to Add

pl = Payload Data List (Seals)
  or
ps = Payload Seals

ds = Delegator Event Seal		

ct = Configuration Trait		

rd = Merkle Tree Root Digest

eo = Establishment Only

ee = Last Establishment Event

dd = Delegated (iffy, this one)

dp = Delegator Prefix

**Comment by SmithSamuelM** [comment]
I edited the table in the original post to include your suggestions.  I don think we need to distinguish event digest etc because its clear from the context where they appear in seals what type of digest they are.  This leaves those codes free for other future uses.

My new favorite is as follows:

| Label | Description                                           | New |
|-------|-------------------------------------|-----|
| vs    | Version String                                        | vs  |
| pre   | Identifier Prefix                                     |ip  | 
| sn    | Sequence Number                                       | sn  |
| ilk   | Message Kind                                          | mk  | 
| dig   | Previous Event Digest, Event Digest, Seal Digest      | dg  |
| sith  | Signing Threshold                                     | st  | 
| keys  | List of Signing Keys                                  | kl  | 
| nxt   | Next Key Set Commitment                               | nk |
| toad  | Threshold of Accountable Duplicity, Witness Threshold | wt  |
| wits  | List of Witnesses                                     | wl  | 
| cnfg  | Configuration Data List                               | cl  |
| cuts  | List of Witnesses to Cut                              | wc  |
| adds  | List of Witnesses to Add                              | wa   |
| data  | Payload Data List (Seal List)                             | pl  | 
| seal  | Delegator Event Seal                                  | ds  |
| trait | Configuration Trait                                   | ct  |
| root  | Merkle Tree Root Digest                               | rd | 
|       | Establishment Only                                    | eo  |   
|       | Last Establishment Event                              | ee  | 
|       | Delegated                                             | dd  |  
|       | Delegator Prefix                                      | dp  |

**Comment by stevetodd** [comment]
In looking at @SmithSamuelM's and @dlandi's proposals and thoughts, I would like to add that the ordering of fields, including order prominence and proximity to other fields, and the values themselves provide context to readers about what the field is. Also, knowing that the structure describes aspects of KERI such as identifiers, keys, witnesses, etc. provides additional context too. Accordingly, I propose that the following:

|Label|Description|Proposed|Notes|
|---|---|---|---|
|vs|Version String|v|
|pre|Identifier Prefix|i|
|sn|Sequence Number|s|_s_equence|
|ilk|Message Kind|t|_t_ype so we can use k for keys|
|dig|Previous Event Digest, Event Digest, Seal Digest|p|_p_revious
|sith|Signing Threshold|kt|relates the _t_hreshold to field k|
|keys|List of Signing Keys|k|
|nxt|Next Key Set Commitment|n|
|toad|Threshold of Accountable Duplicity, Witness Threshold|wt|
|wits|List of Witnesses|w|
|cnfg|Configuration Data List|c|
|cuts|List of Witnesses to Cut|w-|if not w-, then wx|
|adds|List of Witnesses to Add|w+|if not w+, then wa for _a_dd|
|data|Payload Data List (Seal List)|d|
|seal|Delegator Event Seal|dseal|
|trait|Configuration Trait|trait|
|root|Merkle Tree Root Digest|root|
|EstOnly|Establishment Only|EstOnly||
||Last Establishment Event|??|I'm not sure the context|
||Delegated|dd|
||Delegator Prefix|di|_d_elegator _i_dentifier|

Where context doesn't provide any information, I propose that we use longer identifiers, though I don't have strong proposals for those. I think basically every label in config data and payload data should have more descriptive labels. This will make it easier to read them and perhaps provide a degree of safety against collisions among types of entries.

I'm not sold on 'q' for sequence number, but 

To illustrate the context providing clues, here's some examples:

### Inception
```json
{
  "v"  : "KERI10JSON00011c_",
  "i"  : "AaU6JR2nmwyZ-i0d8JZAoTNZH3ULvYAfSVPzhzS6b5CM",
  "s"  : "0",
  "t"  : "icp",
  "kt" : "1",
  "k"  : ["AaU6JR2nmwyZ-i0d8JZAoTNZH3ULvYAfSVPzhzS6b5CM"],
  "n"  : "DZ-i0d8JZAoTNZH3ULvaU6JR2nmwyYAfSVPzhzS6b5CM",
  "wt" : "1",
  "w" : [],
  "c" : []
}

```

### Rotation
```json
{
  "v"  : "KERI10JSON00011c_",
  "i"  : "AaU6JR2nmwyZ-i0d8JZAoTNZH3ULvYAfSVPzhzS6b5CM",
  "s"  : "1",
  "t"  : "rot",
  "p"  : "DZ-i0d8JZAoTNZH3ULvaU6JR2nmwyYAfSVPzhzS6b5CM",
  "kt" : "1",
  "k"  : ["AaU6JR2nmwyZ-i0d8JZAoTNZH3ULvYAfSVPzhzS6b5CM"],
  "n"  : "DZ-i0d8JZAoTNZH3ULvaU6JR2nmwyYAfSVPzhzS6b5CM",
  "wt" : "1",  // lowercase hex string no leading zeros
  "w-" : [],  // list of qualified Base64
  "w+" : [],  // list of qualified Base64
  "d"  : []  // list of seal ordered mappings
}
```

### Interaction
```json
{
  "v" : "KERI10JSON00011c_",
  "i" : "AaU6JR2nmwyZ-i0d8JZAoTNZH3ULvYAfSVPzhzS6b5CM",
  "s" : "2",
  "t" : "ixn",
  "p" : "DZ-i0d8JZAoTNZH3ULvaU6JR2nmwyYAfSVPzhzS6b5CM",
  "d" : []
}
```

### Delegating Interaction Event
```json
{
  "v" : "KERI10JSON00011c_",
  "i" : "AaU6JR2nmwyZ-i0d8JZAoTNZH3ULvYAfSVPzhzS6b5CM",
  "s" : "1",
  "t" : "ixn",
  "p" : "DZ-i0d8JZAoTNZH3ULvaU6JR2nmwyYAfSVPzhzS6b5CM",
  "d" : [  // list of seal ordered mappings
    {
      "i" : "AaU6JR2nmwyZ-i0d8JZAoTNZH3ULvYAfSVPzhzS6b5CM",
      "e" : "DZ-i0d8JZAoTNZH3ULvaU6JR2nmwyYAfSVPzhzS6b5CM", // 'e' for event
    }
  ] 
}
```

...etc.

**Comment by dlandi** [comment]
I like @stevetodd 's proposal. It provides brevity where the meaning is clear; and, clarity where a longer identifier is necessary. All told, this should still deliver an overall savings is record size for the event log as a whole.

As long a "guide" is published for developers and downstream consumers, I think this is a win-win.

**Comment by SmithSamuelM** [comment]
I like the w+ and w-

**Comment by SmithSamuelM** [comment]
@stevetodd 

I just created an issue for the new key state message  https://github.com/decentralized-identity/keri/issues/77

There are some new fields.  How would you update your proposal to accommodate those?

**Comment by chunningham** [comment]
I support @stevetodd's proposal as well, a table to describe them is sufficient for enough understanding to work with it IMO and it has extra size savings

**Comment by SmithSamuelM** [comment]
Thinking about it some more. The configuration data list is a list of maps. But currently we have only one defined map that is a configuration trait as the traits are either expressed or not, effectively boolean. In order to ensure extraction uniqueness in the inception event they have different values. If we only have traits that are either expressed or not in the list then its redundant to have each item in the list be a map with the same structure but different value we could just as well have a list of configuration labels.    This means that instead of (using the longer labels for clarity)

```json

{
...
"cnfg": [
          { 
              "trait":  "EstOnly"
          }
         ],

...
}
```

We would instead have

```json

{
...
"cnfg": ["EstOnly" ],

...
}
```

or using compact labels

```json

{
...
"c": ["eo" ],

...
}
```

**Comment by SmithSamuelM** [comment]
@stevetodd   I generally like the table you suggested. The one I would change is the digest.  I would use "d" instead of "p".
The reason is that digests occur in numerous places but not all cases are digest of the previous event but in all cases what the digest is of is clear from the context. This makes it easier to remember that "d" is digest.

**Comment by SmithSamuelM** [comment]
There does not seem to be any objection to 1 char labels when it is clear from context. Although it does create more friction in picking labels due to the limited choices.  Here is a revised version of Steve's list.  

|Label|Description|Proposed|Notes|
|---|---|---|---|
|vs|Version String|v|
|pre|Identifier Prefix|i|
|sn|Sequence Number|s|
|ilk|Message Type|t|  
|dig|Previous Event Digest, Event Digest, Seal Digest|d|  d for digest universal, type is clear from context except one |
|sith|Signing Threshold, Keys Element Threshold |kt|  uses k from the keys field for the threshold|
|keys|List of Signing Keys|k|
|nxt|Next Key Set Commitment|n|
|toad|Threshold of Accountable Duplicity, Witness Threshold|wt|
|wits|List of Witnesses|w|
|cnfg|Configuration Data List|c|
|cuts|List of Witnesses to Cut|w-|
|adds|List of Witnesses to Add|w+|
|data|Payload Data List (Seal List)|p|
|seal|Delegator Event Seal|s| seal  type is clear from context
|trait|Configuration Trait|ct| may not need if adopt change in structure of  cnfg list|
|root|Merkle Tree Root Digest|rd|  only context where digest type is not clear |
|EstOnly|Establishment Only|EstOnly| eo |
||Last Establishment Event|le|
||Delegated|dd| may not need, empty delegator prefix is sufficient to know
||Delegator Identifier  Prefix|di|

**Comment by dlandi** [comment]
@SmithSamuelM Looks good.

**Comment by stevetodd** [comment]
I would push back on using 'p' vs 'd' for the previous event digest in events. I think it's fine to use 'd' in the seal. I also don't think it's problematic to use 'p' in events and 'd' in seals since the meaning and context is different for each. 

To further explain, reading the 'd' for digest in event leads the reader to the question of "it's the digest of what?" It's like naming a field 'number'. In the seal, the context is that the seal describes the coordinates of the event in a log. The question of what the digest is of is clearer.

I would recommend a field list per seal type, with consistent naming across each where the field names do have the same meaning and context. As an aside, I would also recommend a more consistent scheme for identifying the seal types since right now the recognition logic is inconsistent for each type.

**Comment by SmithSamuelM** [comment]
@stevetodd   You misunderstand  my proposal is to use "d" everywhere for digests and never "p" for digests anywhere.
because "p" is used for "payload"

that way we don't swap and use p and d differently in different contexts. There is no need to swap. IMHO be consistent and never use a letter for two different things.

**Comment by SmithSamuelM** [comment]
I edited the original post since the last comments so please review. 
I think this is a reasonable synthesis of the 3 proposals.


@stevetodd   Not sure what you mean 
> "I would recommend a field list per seal type, with consistent naming across each where the field names do have the same > meaning and context. As an aside, I would also recommend a more consistent scheme for identifying the seal types since > right now the recognition logic is inconsistent for each type."

Each seal type is easy to recognize by the context of where it appears and the elements in the seal, except for the digest seal and root digest seal. As defined field list set in the seals is unique for each seal type. there is no ambiguity.

**Comment by sethjback** [comment]
Looks good!

**Comment by chunningham** [comment]
I sympathise with @stevetodd's point about "digest of what", might I suggest `b` for `backhash`, for the previous event digest?

**Comment by stevetodd** [comment]
**Event Digests and Payloads/List of Seals**

I can live with `d`. I think my concern is that sometimes `d` refers to a digest of the event referenced by the adjacent `s` and sometimes it refers to the event at `s - 1`. If payload weren't assigned 'p', then I would use `d` for the former and `p` for the latter. However, after reviewing delegation again, I see that context can resolve the difference. 

In considering `p`, I wonder if it will always only contain seals and similar attestations? I also wonder if we can through naming better indicate the linkage between the `a` in delegated events and `p` in delegating events? Something silly might be `a^` instead of `a` for anchor, `a` for anchors/attestations instead of `p`. 

**Key State Message**

_Usage of `a`_

Another place where there is differing semantics is the usage of `a` in Key State Messages. It expresses a reference to an event, but it's not referencing the location of a seal like in delegated events. Maybe using something like about for an event reference, we use `k^` as in key reference.

_Referencing the last event and last establishment event_

I'd offer up a tweak to resolve the dual ilk/kind/type fields. It would look like this in the transferrable identifier case:

```json
{
  "v"  : "1.0",  
  "i"  : "EaU6JR2nmwyZ-i0d8JZAoTNZH3ULvYAfSVPzhzS6b5CM", 
  "t"  : "ksn",  
  "kt" : "1", 
  "k"  : ["DaU6JR2nmwyZ-i0d8JZAoTNZH3ULvYAfSVPzhzS6b5CM"],  
  "n"  : "EZ-i0d8JZAoTNZH3ULvaU6JR2nmwyYAfSVPzhzS6b5CM",  
  "wt" : "1",  
  "w"  : ["DnmwyYAfSVPzhzS6b5CMZ-i0d8JZAoTNZH3ULvaU6JR2"], 
  "di" : "",
  "c"  : ["eo"],
  "e"  :
         {
           "s" : "0",
           "t" : "rot",
           "d" : "EAoTNZH3ULvaU6JR2nmwyYAfSVPzhzZ-i0d8JZS6b5CM"
         },
  "ee" : 
         {
           "s":  "1",
           "d":  "EAoTNZH3ULvaU6JR2nmwyYAfSVPzhzZ-i0d8JZS6b5CM"
         },
  "k^" :
         {
           "i":  "EJZAoTNZH3ULvYAfSVPzhzS6b5aU6JR2nmwyZ-i0d8CM",
           "s":  "1",
           "d":  "EULvaU6JR2nmwyAoTNZH3YAfSVPzhzZ-i0d8JZS6b5CM"
         }
}
```
Essentially, the last event fields would be moved under an object at `e`. Also, I'm not sure we need to differentiate the version field with `vs` since the format will be clear by context.

**Comment by SmithSamuelM** [comment]
Anchors
a^  how about "al" for anchor list?  or  
If triggers  a desire to use  a letter code for lists.

Key State Message;
The tweak makes sense. I could go for that.

I just realized that using symbols in the labels like w+ w- will cause problems in JSON dict to object mappers because attributes labels in object in many languages do not allow non alphanumerics.

**Comment by SmithSamuelM** [comment]
Hopefully this makes us close.  We can bike shed on this indefinitely.

**Comment by henkvancann** [comment]
In general, I suggest to avoid the use of characters that look similar like 0 (zero), O (capital o), I (capital i), l (lower case L). For the same reason as Base58 cut them out of Base64.

**Comment by stevetodd** [comment]
I think we're close. Adding more characters to gain better readability is an easy choice to me.

### Non-alphanumeric symbols bad for object mappers

I thought non-alphanumerics might cause people pause. I don't think it really affects anyone but the JS guys—seems to be fine for python, rust, go, and java. The fields are all renamed during parsing anyway in keriox, kerigo, and jkeri. I'm also not really sure if there has been any movement kerijs.

If we do switch from `w+` and `w-`, I suggest we do `wr` (witness remove) instead of `wc`? Cuts has always thrown me, whereas "remove" is a _much_ more common opposite word for "add" in programming. I imagine `cuts` is a relic of looking for a short word for the label originally.

### Anchors

I like the middle proposal:
* `da` for delegator anchor (was: ``)
* `ds` for delegator seal (was:  `` )
* `a` for anchors 
* `p` for prior event digests in events and delegating event location seals
* `d` for event digests

**Comment by dlandi** [comment]
@SmithSamuelM  I think we can leave as is, but per @stevetodd comments where we need to expand to a two or three or four letter code for the sake of clarity we should do it, to let necessity be our guide and minimalism be our goal.

**Comment by dlandi** [comment]
"cut" has also bothered me. I vote for "wr" instead of "wc".

**Comment by SmithSamuelM** [comment]
The + - ^ Symbols are a problem for python identifiers. The only symbols allowed are a-z,0-9 and _

I am good with wr.  Yes cut was shorthand for remove.

**Comment by SmithSamuelM** [comment]
I think I captured all the changes now.  Whoosh 😅 .  So unless anyone objects ...

It's done

**Comment by stevetodd** [comment]
I would recommend letting it sit to allow people in non-US-time-zones to evaluate before closing.

**Comment by chunningham** [comment]
I like the list, would point out that `remove witness` cell currently says `war` instead of `wr` but thats just a typo

**Comment by SmithSamuelM** [comment]
@chunningham  fixed war to wr.  That's auto correct on my iPad at work.

**Comment by stevetodd** [comment]
At the risk of being ridiculed, if you can handle one last suggestion, configuration (`c`) is quite generic and undescriptive. It purpose has really eluded me until this issue. It seems to parallel file modes (i.e. drwxrwxrwx) in POSIX environments. Perhaps modes (`m`) might better describe the field.

The only mode I know of right now is "Establishment Only" `eo`, though I think I saw referenced somewhere thoughts on a "No Delegation" mode, too. Seems to fit the metaphor.

**Comment by SmithSamuelM** [comment]
Its not ridiculous but mode is also generic. I avoided using mode intentionally to avoid confusion with the indirect and direct modes of operation.  But the configuration mode is not an unreasonable description.

**Comment by dlandi** [comment]
How about "cm" for "configuration mode"? To me configuration and mode are not synonymous.

**Comment by dlandi** [comment]
Actually, "configuration mode" sounds unhelpful. Perhaps something more descriptive?

**Comment by SmithSamuelM** [comment]
the configuration list is meant to be a catchall of configuration options. So maybe option "o" for configuration options

**Comment by SmithSamuelM** [comment]
In the white paper they are called configuration traits.

**Comment by SmithSamuelM** [comment]
But we could do the same circular nitpicking about many other things in the list of labels. At some point it does become ridiculous. We are using one letter codes that should be unique and hopefully evocative. There are going to be tradeoffs as we have already made.  So the cnfg is what is being used now. So c matches the existing field so the presumption should be c unless something else is just clearly superior. Which doesn't appear to be so I say lets let sleeping dogs alone.

**Comment by henkvancann** [comment]
> the configuration list is meant to be a catchall of configuration options. So maybe option "o" for configuration options

is it going to be o, O or 0?  :)  See my remark above, stick to Base58 character restrictions?

**Comment by SmithSamuelM** [comment]
So it seems there is no convergence. So leave at "c" and be done with it.

So if you have a strong objection voice it now. We will decide at the meeting next Tuesday to accept or not.

**Comment by SmithSamuelM** [comment]
A markdown version of the proposed labels table and examples has been pushed
https://github.com/decentralized-identity/keri/pull/80

**Comment by bumblefudge** [comment]
Review period closed, already merged.
