### ISSUE TITLE
New Count codes for Replay Mode

### ISSUE THREAD

**Issue by bumblefudge** [decentralized-identity/keri#91]
think thru --> py --> other implementation s --> spec :D

**Comment by stevetodd** [comment]
Just to get the ball rolling on this:

If I understood correctly, the issue is to create a distinct encoding of the count of witness signatures that would allow for appending both controller signatures and witness signatures to an event message. This is applicable, for example, when events are replayed from a witness to a validator. Having a separate code would allow for the signatures from controllers and witnesses to be efficiently communicated. Essentially, the message would be composed as:

<table>
<th colspan=3>Event Message
<tr>
<td>Event
<td>Controller Signatures
<td>Witness Signatures
</table>

I'm not sure if the intent on the signature code prefix being `-` was to keep the code within the bounds of URL safe base64, but if that is the case, I would suggest using`_` to prefix the witness signature count. 

This structure, however, does leave open the question of do we always require a message to have both a signature count and a witness count.  If we don't, we won't know if we have the entire message.

**Comment by stevetodd** [comment]
In the meeting today, we decided to push this off until we start working on indirect mode.

**Comment by chunningham** [comment]
this has been defined in KID0001 and KID0001 commentary
