### ISSUE TITLE
KERI Q&A

### ISSUE THREAD

**Issue by SmithSamuelM** [decentralized-identity/keri#93]
@henkvancann 

Many of the questions in the Q&A revolve around statements like why is KERI reinventing the wheel. Or why is KERI not using blockchain or how can KERI solve some problem that block chain solves.

I think preface to these questions along the following might help.

KERI attempts to solve the "secure attribution" problem. One way of stating this problem is that we want to be able to securely integrally attribute any statement to its source.  Fundamentally non-repudiable digital signatures do that but with one caveat. A digital signature is only a mechanism of secure attribution to the entity that controls or is in possession of the associated private key.  If more than one entity holds that private key then we may no longer securely attribute any statement signed with that key to a given controlling entity. What KERI recognizes is that we can't guarantee secure attribution given key compromise. But we can make a lesser guarantee. That is we can detect key compromise when it happens or at least before it may harm any validator that wishes to act on a supposedly securely attributed statement. This lesser guarantee is provided by something called duplicity detection.  A digitally signed statement is non-repudiable to the set of entities that have possession of the private key. Thus a key compromise may be seen as a malicious expansion of the set of entities that possess the private key from a purported set.  For some entity to benefit from gaining control of a private key, they must make signed statements with that key. These are still non-repudiable to the set of possessors of the private key, its just that the set  may include malicious actors once the key has been compromised. 

KERI primarily cares about statements about the key state of an identifier. So the key events in KERI are signed statements about key state. The construction of key event messages in Keri is deign to leave no ambiguity about key state. All the statements belong to a hash chained signed data structure we call a KEY Event log. One may not make an inconsistent statement about KEY State with respect to a given KEL without it being detectable as inconsistent. One merely needs a copy of the KEL and given this copy any statement  is either provably inconsistent, provably consistent or unconnected. When A set of consistent statement about key state are assembled they form a KEL. Any two versions of a key event log where all events are not identical means that the KEL are duplicitous.. And duplicity detection mechanisms do not require a totally wording distributed consensus algorithm. An immutable event log of key event messages is sufficient.  So KERI says either we can make secure attribution when there is no detected duplicity or we detect duplicity and we no longer can make secure attribution because we have proof that the keys have been compromised by virtue of the duplicity (or equivalently that the set of possessors of the private key includes a malicious actor who is acting duplicitously).  

Given duplicity has been detected the remaining question is how to resolve it. The easy answer is don't trust. The harder answer is resolve the duplicity such that one version may be appraised as the trusted one. Many of the elements of KERI are mechanisms to allow unambiguous resolution of duplicity via recovery from the associated key compromise. But KERI does not guarantee that all duplicity is resolvable or recoverable merely that it is detectable and once detected any validator may be protected from harm by not trusting any statements with unresolved duplicity.  In contrast a distributed consensus ledger is not solving the secure attribution problem. It is solving the total ordering problem. These problems are not the same and hence the solutions may be very different in spite of some similarities.

**Comment by henkvancann** [comment]
The challenge is that any critic could use sweeping statement like "KERI claims to solve a proven unsolvable problem"  and answers like the one above are unreadable, incomprehensible. We need simple language that is still correct.

I like your analogy here
<img width="821" alt="Screenshot 2021-02-03 at 22 27 00" src="https://user-images.githubusercontent.com/479356/106812861-89406080-6670-11eb-97e8-ca2a92849a2f.png">

Could we invent more of those?

**Comment by SmithSamuelM** [comment]
With new tech like KERI there is a vetting process. Enough experts look at the tech and evaluate it and at some point make simple statements that it works These enable resources to be applied to the tech.. Naysayers and detractors also make simple statement that it can't work. Eventually showing that it actually works is what shuts up the naysayers.  So at this stage we need to get mind share from enough experts to get resources while building as fast as we can so that we can shut up the naysayers.  So KERI uses duplicity detection which is a simpler tech than ledgers to protect users. Is a one line summary that does not define what duplicity detection is.  But simple statement tend to not define or really explain things they just label what is new.

**Comment by bumblefudge** [comment]
I definitely agree that explaining duplicity detection positively is a way to get out from under "why is this better than status quo?" questions which are kind of an unwinnable framing.  I am not sure I even understand the duplicity detection mechanics very well, though, so feel free to use me as a guinea pig for your best "explain it to me like I'm five" explanations of it 😄

**Comment by henkvancann** [comment]
Yep. Ik would like to create a mapping of simple language which will NOT do the job you think is needed (get mind share from enough experts to get resources while building as fast as we can..) and if you click on the simple sentences, they will explode to the detailed explanation that will convince the experts.
===
KERI attempts to solve the "secure attribution" problem. One way of stating this problem is that we want to be able to securely integrally attribute any statement to its source.  ->
KERI knows shit who said wot.

Fundamentally non-repudiable digital signatures do that but with one caveat. A digital signature is only a mechanism of secure attribution to the entity that controls or is in possession of the associated private key. If more than one entity holds that private key then we may no longer securely attribute any statement signed with that key to a given controlling entity.  -> 
But if it’s a multi-headed monster it gets messy

What KERI recognizes is that we can't guarantee secure attribution given key compromise. But we can make a lesser guarantee. That is we can detect key compromise when it happens or at least before it may harm any validator that wishes to act on a supposedly securely attributed statement. -> 
KERI knows when it can't be sure. But if someone tries to cheat, we catch them before they become dangerous.
===
So you see this: 
[KERI knows shit who said wot.] [But if it’s a multi-headed monster chattering around, it gets messy.] [KERI knows when it can't be sure. But if someone tries to cheat, we catch them before they become dangerous.]

But with one click on [...] you will get the real deal ;)

**Comment by henkvancann** [comment]
> I definitely agree that explaining duplicity detection positively is a way to get out from under "why is this better than status quo?" questions which are kind of an unwinnable framing. I am not sure I even understand the duplicity detection mechanics very well, though, so feel free to use me as a guinea pig for your best "explain it to me like I'm five" explanations of it 😄

'unwinnable framing', right, but could we try to steer / guide the framing? So that an image consolidates that early KERI-adopters can relate to?
Not sure how these processes work, not my cup of tea. But what I do know is that a wrong image can costs loads of wasted energy further down the road answering all the recurring bullshit somebody successfully hooked onto your darling.  E.g. -> https://blockchainbird.com/t/btc/ ; one of our projects trying to debunk bitcoin framing.

**Comment by fimbault** [comment]
I understand the frustration seen in previous comments that you need to boil the ocean to satisfy requests, but I don't think that's the point. There are still a lot of assumptions which are not clarified. 
And as I said on slack, we really appreciate the efforts.

**Comment by fimbault** [comment]
And typically the statements are very broad, so it's hard to make a judgment. To be more specific on the Q&A: 

> Differences between blockchain-based security and KERI security
> * Where KERI doesn't need total ordering in its logs, blockchain do need that. What KERI needs is watchers that construct string of event in the relative order of reception of the KEL {TBW please explain or improve this: what is this, why is it important?}
> * Another characteristic is that KERI identifiers are transferable and blockchain-based identifiers are not, they are bound to their ledger.

I certainly agree that no total ordering is a good idea. I agree with the role of watchers and that you need some kind of "duplicity detection". Yet I still find the architecture overly complex. Cf my comment on witnesses, it's not obvious why that is required.

As for the second characteristic, I would agree with Daniel on : "Any registry with deterministically resolvable entries requires the entry controllers' IDs and resolutions be native to it". It's totally possible to achieve the first goal without the second, and I don't even see why that is considered a problem (apart from a very theorical one).

**Comment by henkvancann** [comment]
The Q-and-A is draft, mainly written by a non-expert (moi). So your concerns are valid, Fabien: the statements are sometimes broad and sometimes lack the proper explanation. That's where I need the experts to step in, because if I try really really hard, I just get it. The reality of an average working day is that experts like to build and not document / defend, and I won't blame anyone for that.
There's no frustration involved on my behalf. I do doc-work for both DIFs Sidetree and KERI and BCCommons' Torgap, and Gordian and FullyNoded, consider myself neutral but driven to make innovative tech well understood.

**Comment by fimbault** [comment]
Yes, and thanks for that. Good documentation is essential.

**Comment by henkvancann** [comment]
I am working on a 'made simple tool' that has a comical twist to it. In my imagination I see Robert de Niro explain KERI to other people and at the same time say to the expert (his 'Doc'):
"You're good, you!"
https://www.youtube.com/watch?v=218iXiKhKlg

So the De Niro persona explains KERI to others:

"
Let's talk about digital you, me and others on the internet: everybody's own identifier, you care about. When we talk about 'who' we mean digital who, identifiers.
--
KERI knows shit who said wot.
But if it’s a multi-headed monster chattering around, it gets messy
KERI knows when it can't be sure. But if some folks try to cheat, we catch them before they can do harm.
And if you is not you, we'll catch the cheat as soon as he steps forward and double speaks. KERI won't forget, when someone double speaks.
KERI watches you, using your identifiers. And tell what ya did to them.
KERI notes what you're up to and everything you did in the past. You told KERI yourself. You signed it, so no bullshitting please.
Anyone with a copy of KERI's notes about your goings on with your identifiers can prove you're talking straight. Sound notes have a name: KEL. If you double speak in two different KELs, KERI got ya.
KERI says we trust you as long as you're straight. KERI never trusts you again, when you or someone acting like you, double speak(s).
KERI helps to choose who can be trusted.
KERI detects double speak, but can't alway say who's right. If so, it's safer to trust nothing anymore.
Blockchains do other stuff; they won't know "who said wot".

**Comment by chunningham** [comment]
the [Q&A documents](https://github.com/decentralized-identity/keri/tree/master/docs) has answered this issue, closing

**Comment by jayzhan211** [comment]
We can use global duplicity log to detect potential duplicated KEL.
How many copies of KEL should we get to ensure there is no duplicity? And, assume we get N copies of them and "trust" it,  but on one day we found that there is duplicity, is there some kind of "rollback" mechanism to undo the "transaction" that based on the trust of this ID
